name: Skunk Worx
favicon: null
layout_spectrum: 0.07540203048847616
typography_spectrum: 0.7610724887344986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9183085113763809
  lightness: 0.3892876880709082
  saturation: 0.6101729592774063
  rhythmicContrast: 0.7167548465076834
purpose: []
